export * from './Banner'
export * from './PainSection'
export * from './WhySection'
export * from './CTAMiddle'
export * from './HowSection'
export * from './CTABottom'
export * from './CommonQuestions'
